export const KLAYTN_HOMEPAGE = 'https://www.klaytn.com/'
export const KLAYTN_SCOPE = 'https://baobab.scope.klaytn.com/'
export const KLAYTN_WALLET = 'https://baobab.wallet.klaytn.com/'
export const KLAYTN_DOCS = 'https://docs.klaytn.com/'
export const KLAY_FAUCET = 'https://baobab.wallet.klaytn.com/access?next=faucet'
export const GROUNDX_HOMEPAGE = 'https://groundx.xyz/'
